/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#include <rpc/rpc.h>

main(argc, argv)
	int argc;
	char *argv[];
{
	char *host;
	CLIENT *handle;
	int *scalers;
	int channels,iclock,i;

	if (argc < 2) {
		printf("usage:  %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];

	if(!(handle=scaserOpen(host))) {
	  fprintf(stderr,"Error connecting to %s\n",host);
	  exit(1);
	}
	scaserClear(handle);

	scaserGetInfo(handle,0,&channels,0,&iclock);

	scalers = (int *) malloc(channels*sizeof(int));
	
	scaserReadScalers(handle, 0, channels, scalers, 0,0);
	for(i=0;i<channels;i++) {
	  printf("%d: %u\n",i,scalers[i]);
	}
	exit(0);
}
