/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "scaserRpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
scaser_clear_1(void *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SCASER_CLEAR,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

INFO *
scaser_getinfo_1(void *argp, CLIENT *clnt)
{
	static INFO clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SCASER_GETINFO,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_INFO, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

VALUES *
scaser_getscalers_1(GETREQUEST *argp, CLIENT *clnt)
{
	static VALUES clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SCASER_GETSCALERS,
		(xdrproc_t) xdr_GETREQUEST, (caddr_t) argp,
		(xdrproc_t) xdr_VALUES, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

VALUES *
scaser_geteorscalers_1(GETREQUEST *argp, CLIENT *clnt)
{
	static VALUES clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SCASER_GETEORSCALERS,
		(xdrproc_t) xdr_GETREQUEST, (caddr_t) argp,
		(xdrproc_t) xdr_VALUES, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
