/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "scaserRpc.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */


void
scaserprog_1(host)
	char *host;
{
	CLIENT *clnt;
	int  *result_1;
	char *  scaser_clear_1_arg;
	INFO  *result_2;
	char *  scaser_getinfo_1_arg;
	VALUES  *result_3;
	GETREQUEST  scaser_getscalers_1_arg;

#ifndef	DEBUG
	clnt = clnt_create(host, SCASERPROG, SCVERS, "netpath");
	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
#endif	/* DEBUG */

	result_1 = scaser_clear_1((void *)&scaser_clear_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror(clnt, "call failed");
	}
	result_2 = scaser_getinfo_1((void *)&scaser_getinfo_1_arg, clnt);
	if (result_2 == (INFO *) NULL) {
		clnt_perror(clnt, "call failed");
	}
	result_3 = scaser_getscalers_1(&scaser_getscalers_1_arg, clnt);
	if (result_3 == (VALUES *) NULL) {
		clnt_perror(clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy(clnt);
#endif		/* DEBUG */
}


main(argc, argv)
	int argc;
	char *argv[];
{
	char *host;

	if (argc < 2) {
		printf("usage:  %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	scaserprog_1(host);
}
